(in-package :cl-user)

(cl-tk:define-gui-function setup-text-toplevel (&optional (text-name ".text"))
  (let ((root-children (cl-tk:tcl "winfo" "children" ".")))
    (unless (or (null root-children)
                (and (stringp root-children) (string= "" root-children)))
      (apply #'cl-tk:tcl "destroy" (alexandria:ensure-list root-children))))
  (let ((vsb (cl-tk:tcl "::ttk::scrollbar" ".vsb" :orient "vertical" :command (list text-name "yview")))
        (hsb (cl-tk:tcl "::ttk::scrollbar" ".hsb" :orient "horizontal" :command (list text-name "xview"))))
    (cl-tk:tcl "grid" (cl-tk:tcl "text" text-name
                                 :xscrollcommand (list hsb "set")
                                 :yscrollcommand (list vsb "set"))
               :sticky "news" :row 0 :column 0)
    (cl-tk:tcl "grid" vsb :sticky "ns" :row 0 :column 1)
    (cl-tk:tcl "grid" hsb :sticky "ew" :row 1 :column 0)
    (cl-tk:tcl "grid" "columnconfigure" "." 0 :weight 1)
    (cl-tk:tcl "grid" "rowconfigure" "." 0 :weight 1)))
